name: Karabiner-MultitouchExtension

targets:
  Karabiner-MultitouchExtension:
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: org.pqrs.Karabiner-MultitouchExtension
      CODE_SIGN_ENTITLEMENTS: ''
      CODE_SIGN_IDENTITY: '-'
      CODE_SIGN_STYLE: Manual
      SYSTEM_HEADER_SEARCH_PATHS:
        - ../../vendor/cget/include
      HEADER_SEARCH_PATHS:
        - ../lib/KarabinerKit/include
        - ../../lib/libkrbn/include
      OTHER_LDFLAGS:
        - -L../lib/KarabinerKit/build/Release
        - -L../../lib/libkrbn/build/Release
        - -lKarabinerKit
        - -lkrbn
      OTHER_SWIFT_FLAGS: '-warnings-as-errors'
    type: application
    platform: macOS
    deploymentTarget: 11.0
    sources:
      - path: src
        compilerFlags:
          - -Wall
          - -Werror
      - path: Resources
        excludes:
          - .gitignore
          - '*.plist.in'
    dependencies:
      - sdk: libc++.tbd
      - framework: /System/Library/PrivateFrameworks/MultitouchSupport.framework
